version: '3.8'
services:
  #############
  ## OPEN VIDU ##
  openvidu:
    image: openvidu/openvidu-dev:2.26.0
    environment:
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
    ports:
      - ${OPENVIDU_PORT}:4443
    networks:
      - webrtc
    restart: always
    container_name: openvidu
  ##############
  ## SERVER ##
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - webapp
      - webrtc
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:3000
    volumes:
      - ./server/src:/app/src
    restart: always
    command: yarn start:dev
    container_name: server
  #############
  ## CLIENT ##
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    networks:
      - webapp
      - webrtc
    ports:
      - ${CLIENT_PORT}:5173
    command: yarn dev
    restart: always
    container_name: client
networks:
  webapp:
    driver: bridge
  webrtc:
    driver: bridge
